export const languages = {
  zh: {
    // Welcome Screen
    appDescription: "承包商的智能排班工具",
    valueProposition: "为承包商和蓝领专业人士\n提供智能排班解决方案",
    signUpFree: "免费注册",
    logIn: "登录",
    joiningTeam: "加入团队？",
    
    // Auth Forms
    welcomeBack: "欢迎回来",
    createAccount: "创建账户",
    
    // Login Form
    continueWithPhone: "使用手机号登录",
    continueWithEmail: "使用邮箱登录",
    continueWithApple: "使用 Apple ID 登录",
    continueWithWechat: "使用微信登录",
    continueWithGoogle: "使用谷歌登录",
    
    // Registration Form
    email: "邮箱",
    password: "密码",
    phoneLogin: "手机验证码登录",
    passwordLogin: "密码登录",
    phoneNumber: "手机号",
    phoneNumberPlaceholder: "请输入您的手机号码",
    passwordPlaceholder: "请输入密码",
    verificationCode: "验证码",
    verificationCodePlaceholder: "请输入验证码",
    getVerificationCode: "获取验证码",
    minimumCharacters: "最少6个字符",
    continue: "继续",
    login: "登录",
    switchToPasswordLogin: "使用密码登录",
    switchToPhoneLogin: "使用验证码登录",
    alreadyHaveAccount: "已有账户？",
    loginHere: "在此登录",
    or: "或",
    agreeToTerms: "我已阅读并同意",
    
    // Company Information
    companyInformation: "公司信息",
    companyName: "公司名称",
    companyNameRequired: "公司名称 *",
    industry: "行业",
    industryRequired: "行业 *",
    selectIndustry: "选择行业",
    construction: "建筑业",
    restaurant: "餐饮业",
    manufacturing: "制造业",
    contactPerson: "联系人",
    contactPersonRequired: "联系人 *",
    fullName: "姓名",
    businessAddress: "营业地址",
    businessAddressRequired: "营业地址 *",
    enterBusinessAddress: "输入营业地址",
    companyDescription: "公司描述",
    optional: "（可选）",
    briefDescription: "简要描述您的公司",
    
    // Phone Verification
    phoneVerification: "手机验证",
    phoneNumber: "手机号码",
    sendCode: "发送验证码",
    resend: "重新发送",
    enterVerificationCode: "输入验证码",
    
    // Terms
    byTapping: "点击\"继续\"，您同意我们的",
    privacyPolicy: "隐私政策",
    and: "和",
    termsOfService: "服务条款",
    byContinuing: "继续使用即表示您同意我们的",
    
    // Onboarding Flow
    welcomeToStaffLink: "欢迎使用劳脉络",
    letsSetupAccount: "让我们开始设置您的账户",
    personalizeExperience: "我们将使用您的信息来设置账户并个性化您的体验",
    step1BasicInfo: "基本信息",
    step2CompanyInfo: "企业信息", 
    step3IndustrySelection: "行业选择",
    step4BusinessDetails: "业务详情",
    step5Complete: "完成设置",
    contactName: "联系人姓名",
    contactNamePlaceholder: "请输入您的姓名",
    emailAddress: "邮箱地址",
    emailAddressOptional: "邮箱地址 (可选)",
    emailPlaceholder: "请输入邮箱地址",
    nextStep: "下一步",
    
    // Step 2 Company Info
    tellUsAboutCompany: "告诉我们您的企业信息",
    companyInfoHelpUs: "这些信息将帮助我们为您提供更好的服务",
    companyNameRequired: "企业名称*",
    enterCompanyName: "请输入企业/公司名称",
    companyType: "企业类型",
    selectCompanyType: "请选择企业类型",
    individualBusiness: "个体工商户",
    limitedCompany: "有限公司",
    partnership: "合伙企业",
    other: "其他",
    businessAddressRequired: "经营地址*",
    enterBusinessAddress: "请输入主要经营地址",
    companyDescription: "企业介绍",
    briefDescriptionCompany: "简单描述您的企业业务 (最多100字)",
    pleaseEnterCompanyName: "请输入企业名称",
    pleaseEnterBusinessAddress: "请输入经营地址",
    
    // Step 3 Industry Selection
    whatIndustryQuestion: "您主要从事什么行业？",
    selectIndustryCustomize: "选择您的主要行业，我们将为您定制相应的功能",
    constructionRenovation: "建筑装修",
    constructionDesc: "水电安装、装修装饰、工程建设",
    foodService: "餐饮服务",
    foodServiceDesc: "餐厅、酒店、茶餐厅、快餐店",
    manufacturing: "制造业",
    manufacturingDesc: "电子制造、服装制造、食品加工",
    logisticsWarehousing: "物流仓储",
    logisticsDesc: "快递分拣、仓库管理、货物搬运",
    otherServices: "其他服务",
    otherServicesDesc: "清洁、保安、维修等服务",
    pleaseSelectIndustry: "请选择您的行业",
    
    // Step 4 Business Setup
    whatSpecificBusinessType: "具体是什么类型的业务？",
    basedOnYourIndustrySelection: "根据您在Step 3选择的行业，请选择具体的业务类型",
    selectSpecificBusinessType: "选择您的具体业务类型：",
    teamSizeQuestion: "团队规模 (可选)",
    howManyWorkersManage: "您通常管理多少工人？",
    pleaseSelectBusinessType: "请选择业务类型",
    
    // Food Service Business Types
    teaRestaurant: "茶餐厅",
    fastFood: "快餐店",
    hotPot: "火锅店",
    chineseRestaurant: "中餐厅",
    westernRestaurant: "西餐厅",
    coffeeShop: "咖啡厅",
    hotelDining: "酒店餐饮",
    takeaway: "外卖店",
    otherFood: "其他餐饮",
    
    // Construction Business Types
    homeDecoration: "家装公司",
    commercialDecoration: "工装公司",
    plumbingElectrical: "水电安装",
    renovationTeam: "装修队",
    constructionTeam: "建筑工程队",
    maintenanceService: "维修服务",
    otherConstruction: "其他建筑",
    
    // Manufacturing Business Types
    electronicsMfg: "电子制造",
    textileMfg: "服装制造",
    foodProcessing: "食品加工",
    autoParts: "汽车零件",
    plasticProducts: "塑料制品",
    metalProcessing: "金属加工",
    otherManufacturing: "其他制造",
    
    // Logistics Business Types
    expressDelivery: "快递配送",
    warehouseMgmt: "仓库管理",
    cargoHandling: "货物搬运",
    freightTransport: "货运运输",
    sortingCenter: "分拣中心",
    otherLogistics: "其他物流",
    
    // Other Service Business Types
    cleaningService: "清洁服务",
    securityService: "保安服务",
    repairService: "维修服务",
    landscaping: "园林绿化",
    propertyMgmt: "物业管理",
    otherService: "其他服务",
    
    // Team Sizes
    teamSize1to10: "1-10人",
    teamSize11to30: "11-30人",
    teamSize31to50: "31-50人",
    teamSize50plus: "50人以上",
    
    // Step 5 Complete
    completeSetup: "完成设置",
    lastStepSetPassword: "最后一步，为您的账户设置登录密码",
    setLoginPassword: "设置登录密码",
    enterPassword6to20: "请设置6-20位登录密码",
    confirmPassword: "确认密码",
    enterPasswordAgain: "请再次输入密码",
    completeRegistration: "完成注册",
    passwordMinLength: "密码至少6位字符",
    passwordsDoNotMatch: "两次输入的密码不一致",
    
    // Dashboard & Navigation
    home: "首页",
    goodMorning: "早上好",
    yourCompany: "您的企业",
    todayOverview: "今日概览",
    activeProjects: "进行中项目",
    workersToday: "今日工人",
    completedTasks: "已完成任务",
    myProjects: "我的项目",
    seeAll: "查看全部",
    noProjectsYet: "暂无项目",
    clickToAddFirstProject: "点击添加您的第一个项目",
    newProject: "新建项目",
    quickActions: "快捷操作",
    viewSchedule: "查看排班",
    manageWorkers: "管理工人",
    settings: "设置",
    reports: "报表",
    
    // Projects Screen
    projects: "项目",
    searchProjects: "搜索项目...",
    all: "全部",
    active: "进行中",
    completed: "已完成",
    startByCreatingFirstProject: "开始创建您的第一个项目",
    createFirstProject: "创建第一个项目",
    
    // Workers Screen
    workers: "工人",
    totalWorkers: "总工人数",
    activeToday: "今日在班",
    available: "可调度",
    searchWorkers: "搜索工人",
    noWorkersYet: "暂无工人",
    addWorkersToStartScheduling: "添加工人开始排班",
    addFirstWorker: "添加第一个工人",
    
    // Profile Screen
    profile: "我的",
    userName: "用户姓名",
    editProfile: "编辑资料",
    account: "账户",
    personalInfo: "个人信息",
    companySettings: "企业设置",
    changePassword: "修改密码",
    preferences: "偏好设置",
    notifications: "通知设置",
    darkMode: "深色模式",
    off: "关闭",
    support: "帮助支持",
    help: "帮助",
    feedback: "意见反馈",
    about: "关于",
    logout: "退出登录",
    version: "版本",
    confirmLogout: "确认退出",
    logoutConfirmMessage: "确定要退出登录吗？",
    cancel: "取消",
    ok: "确定",
    
    // Create Project Screen
    createProject: "创建项目",
    projectName: "项目名称",
    enterProjectName: "请输入项目名称",
    projectAddress: "项目地址",
    enterProjectAddress: "请输入项目地址",
    startDate: "开始日期",
    endDate: "结束日期",
    selectDate: "选择日期",
    projectDescription: "项目描述",
    enterProjectDescription: "请输入项目描述",
    assignWorkers: "分配工人",
    scheduleWork: "安排工作",
    addPhotos: "添加照片",
    pleaseEnterProjectName: "请输入项目名称",
    pleaseEnterProjectAddress: "请输入项目地址",
    success: "成功",
    projectCreatedSuccessfully: "项目创建成功",
    
    // Project Creation Wizard
    projectBasicInfo: "项目基础信息",
    timeSchedule: "时间安排",
    workRequirements: "工作要求",
    selectWorkers: "选择工人",
    confirmSend: "确认发送",
    pleaseSelectProjectType: "请选择项目类型",
    
    // Project Types - Industry Categories
    constructionRenovation: "建筑装修",
    foodService: "餐饮服务", 
    manufacturing: "制造加工",
    logisticsWarehousing: "物流仓储",
    generalServices: "综合服务",

    // Construction & Renovation
    homeRenovation: "家庭装修",
    homeRenovationDesc: "住宅翻新、厨卫改造、局部装修",
    commercialRenovation: "商业装修", 
    commercialRenovationDesc: "办公室、店铺、餐厅装修",
    electricalPlumbing: "水电工程",
    electricalPlumbingDesc: "电路改造、水管安装、弱电布线",
    maintenanceService: "维修服务",
    maintenanceServiceDesc: "设备维修、故障排除、日常维护", 
    constructionProject: "建筑工程",
    constructionProjectDesc: "土建施工、基础建设、结构工程",

    // Food & Beverage
    coffeeTea: "咖啡茶饮",
    coffeeTeaDesc: "咖啡厅、奶茶店、茶餐厅",
    chineseCuisine: "中式餐饮",
    chineseCuisineDesc: "中餐厅、面馆、粥店", 
    fastFood: "快餐连锁",
    fastFoodDesc: "快餐店、外卖店",
    hotpotBBQ: "火锅烧烤", 
    hotpotBBQDesc: "火锅店、烧烤店、麻辣烫",
    hotelDining: "酒店餐饮",
    hotelDiningDesc: "酒店餐厅、宴会厅",

    // Manufacturing
    electronicsMfg: "电子制造",
    electronicsMfgDesc: "手机组装、电子产品生产",
    textileMfg: "服装纺织", 
    textileMfgDesc: "服装加工、纺织品生产",
    foodProcessing: "食品加工",
    foodProcessingDesc: "食品厂、饮料厂、包装",
    mechanicalMfg: "机械制造",
    mechanicalMfgDesc: "设备制造、零件加工",
    packagingPrinting: "包装印刷",
    packagingPrintingDesc: "包装材料、印刷品制作",

    // Logistics & Warehousing  
    expressDelivery: "快递配送",
    expressDeliveryDesc: "快递分拣、配送、收派",
    warehouseOps: "仓库作业", 
    warehouseOpsDesc: "入库、出库、盘点、理货",
    movingService: "搬家服务",
    movingServiceDesc: "居民搬家、办公室搬迁",
    freightHandling: "货运装卸",
    freightHandlingDesc: "长途货运、装卸作业",
    inventoryMgmt: "库存管理", 
    inventoryMgmtDesc: "仓储管理、库存盘点",

    // General Services
    cleaningService: "清洁保洁",
    cleaningServiceDesc: "办公楼清洁、住宅保洁、深度清洁",
    securityService: "安保服务",
    securityServiceDesc: "物业保安、活动安保、巡逻", 
    landscaping: "园林绿化",
    landscapingDesc: "绿化养护、景观维护、修剪",
    eventService: "活动服务",
    eventServiceDesc: "会展布置、庆典活动、临时服务",
    emergencyService: "应急服务",
    emergencyServiceDesc: "紧急维修、临时用工、突发需求",
    
    // Priority
    projectPriority: "项目优先级",
    normalPriority: "普通",
    urgentPriority: "紧急",
    emergencyPriority: "加急",
    sendNotification: "发送通知",
    
    // Common
    required: "*",
    back: "返回",
    error: "错误",
    pleaseEnterName: "请输入姓名",
    pleaseEnterPhone: "请输入手机号码",
    freeTrialActivated: "您的免费试用已激活",
    pleaseAgreeToTerms: "请先同意服务协议和隐私协议",
    pleaseCompleteAllFields: "请填写完整信息",
    pleaseGetVerificationCode: "请先获取验证码",
    verificationFailed: "验证失败",
    incorrectVerificationCode: "验证码错误",
    networkError: "网络错误，请稍后重试",
    sendFailed: "发送失败",
    pleaseTryAgainLater: "请稍后重试",
    loginSuccess: "登录成功",
    loginWith: "使用",
    successful: "登录成功",
    loginFailed: "登录失败",
    
    // Smart Button Text
    startFillingProject: "开始填写项目信息",
    needToFillMore: "还需填写{count}项",
    continueToTimeSchedule: "继续到时间安排",
    continueToWorkRequirements: "继续到工作需求",
    
    // Language
    language: "语言",
    chinese: "简体中文",
    english: "English",
    
    // Date and Time
    today: "今天",
    tomorrow: "明天",
    selectDate: "选择日期",
    selectTime: "选择时间",
    monday: "周一",
    tuesday: "周二", 
    wednesday: "周三",
    thursday: "周四",
    friday: "周五",
    saturday: "周六",
    sunday: "周日",
    
    // Project Types
    projectType: "项目类型",
    projectTypeRequired: "项目类型*",
    selectProjectTypeFirst: "请先选择项目的时间性质",
    onetimeProject: "一次性项目",
    onetimeProjectDesc: "在指定的日期范围内完成",
    recurringProject: "重复性项目", 
    recurringProjectDesc: "每周固定时间重复进行",
    
    // Time Schedule
    projectPeriod: "项目周期",
    projectTimeRange: "项目时间范围",
    setProjectStartEnd: "设置重复项目的整体周期",
    setProjectDates: "设置项目的开始和结束日期",
    startDateRequired: "开始日期*",
    endDateRequired: "结束日期*",
    selectStartDate: "选择开始日期",
    selectEndDate: "选择结束日期",
    dailyWorkTime: "每日工作时间",
    eachWorkTime: "每次工作时间",
    setDailyTimeRange: "设置每天的工作时间段",
    setEachTimeRange: "设置每次工作的时间段",
    startTime: "开始时间",
    endTime: "结束时间",
    recurringWorkDays: "重复工作日*",
    selectWeeklyDays: "选择每周需要工作的日期",
    timeNotes: "时间备注",
    addTimeNotes: "添加时间安排的特殊说明...",
    endDateBeforeStart: "结束日期不能早于开始日期",
    fillCompleteTimeInfo: "请填写完整的时间安排信息",
    
    // Work Requirements
    requiredSkillsLabel: "所需技能*",
    selectRequiredSkills: "选择项目需要的技能类型",
    requiredWorkersLabel: "需要人数*",
    selectWorkerCount: "请选择需要的工人数量",
    
    // Worker Count Options
    workerRange11to20: "11-20人",
    workerRange21to50: "21-50人", 
    workerRange51to100: "51-100人",
    workerRange100plus: "100人以上",
    enterExactCount: "请输入具体人数",
    peopleCount: "人",
    customWorkerCount: "自定义人数",
    experienceRequirement: "经验要求",
    selectExperienceLevel: "选择对工人经验的要求",
    workDescriptionLabel: "工作描述*",
    workDescriptionSubtitle: "详细描述需要完成的工作内容",
    workDescriptionPlaceholder: "请详细描述工作内容、要求和注意事项...",
    salarySettings: "薪酬设置",
    selectPaymentMethod: "选择薪酬结算方式",
    hourlyPayment: "按小时结算",
    hourlyPaymentDesc: "每小时的工作费用",
    dailyPayment: "按天结算", 
    dailyPaymentDesc: "每天的工作费用",
    totalProjectPayment: "一口价",
    totalProjectPaymentDesc: "整个项目的总费用",
    hourlyWage: "小时工资(元/小时)",
    dailyWage: "日工资(元/天)",
    projectTotal: "一口价(元)",
    enterHourlyWage: "输入每小时工资",
    enterDailyWage: "输入每天工资", 
    enterProjectTotal: "输入一口价",
    specialRequirementsLabel: "特殊要求",
    specialRequirementsSubtitle: "其他特殊要求或注意事项",
    specialRequirementsPlaceholder: "如：需要自带工具、特殊时间要求等...",
    fillCompleteWorkInfo: "请填写完整的工作要求信息",
    
    // Skills - Construction & Renovation
    plumbingInstall: "水电安装",
    electrician: "电工",
    carpentry: "木工", 
    painting: "油漆",
    tiling: "铺砖",
    masonry: "泥瓦工",
    waterproofing: "防水工",
    ceilingInstall: "吊顶工",
    glassInstall: "玻璃安装工",
    plumber: "水工",
    pipeInstall: "管道工",
    weakCurrent: "弱电工",
    locksmith: "锁匠",
    applianceRepair: "家电维修",
    rebarWorker: "钢筋工",
    concreteWorker: "混凝土工",
    welding: "焊接",
    scaffoldWorker: "架子工",
    surveyor: "测量工",
    
    // Skills - Food & Beverage
    barista: "咖啡师",
    waiter: "服务员",
    cashier: "收银员",
    cleaner: "清洁工",
    chef: "厨师",
    kitchenHelper: "配菜员",
    dishwasher: "洗碗工",
    operator: "操作员",
    deliveryWorker: "配送员",
    bbqChef: "烧烤师",
    foodRunner: "传菜员",
    
    // Skills - Manufacturing
    assemblyWorker: "组装工",
    solderer: "焊接工",
    qualityInspector: "质检员",
    packagingWorker: "包装工",
    machineOperator: "机器操作员",
    sewingWorker: "缝纫工",
    cuttingWorker: "裁剪工",
    ironingWorker: "熨烫工",
    foodProcessor: "食品加工工",
    latheMachinist: "机床操作工",
    assembler: "装配工",
    materialHandler: "搬运工",
    printer: "印刷工",
    bookbinder: "装订工",
    
    // Skills - Logistics & Warehousing
    courier: "快递员",
    sorter: "分拣员",
    loader: "装卸工",
    driver: "司机",
    stocker: "理货员",
    forkliftOperator: "叉车工",
    warehouseKeeper: "仓管员",
    mover: "搬运工",
    packer: "包装工",
    furnitureAssembler: "家具拆装工",
    
    // Skills - General Services
    janitor: "保洁员",
    cleaning: "清洁工",
    windowCleaner: "玻璃清洁工",
    carpetCleaner: "地毯清洁工",
    securityGuard: "保安员",
    doorman: "门卫",
    patrolOfficer: "巡逻员",
    monitorOperator: "监控员",
    gardener: "园艺工",
    treeTrimmer: "修剪工",
    irrigationWorker: "喷灌工",
    planter: "种植工",
    eventSetup: "布置工",
    audioTech: "音响师",
    photographer: "摄影师",
    glazier: "玻璃工",
    tempWorker: "临时工",
    
    // Experience Levels
    beginnerLevel: "初级",
    beginnerDesc: "1年以下经验",
    intermediateLevel: "中级",
    intermediateDesc: "1-3年经验", 
    experiencedLevel: "高级",
    experiencedDesc: "3年以上经验",
    
    // Select Workers
    searchWorkerName: "搜索工人姓名...",
    allWorkers: "全部",
    recommendedWorkers: "推荐",
    availableWorkers: "可接单",
    selectedWorkers: "已选择",
    workersSelected: "已选择 {count} 位工人",
    workerBusyAlert: "该师傅当前忙碌中，无法选择",
    availableStatus: "可接单",
    busyStatus: "忙碌中",
    lastActive: "最后活跃",
    selectAtLeastOneWorker: "请至少选择一位工人",
    noMatchingWorkers: "暂无符合条件的工人",
    adjustSearchFilter: "尝试调整搜索条件或筛选选项",
    
    // Confirm Send
    projectOverview: "项目概览",
    basicInformation: "基础信息",
    projectNameLabel: "项目名称",
    projectTypeLabel: "项目类型", 
    projectAddressLabel: "项目地址",
    workRequirementsInfo: "工作需求",
    timeArrangement: "时间安排",
    salarySettings: "薪酬设置",
    workTimeLabel: "工作时间",
    dailyTimeLabel: "每日时间",
    workRequirementsLabel: "工作要求",
    requiredSkillsLabel: "所需技能",
    requiredWorkersLabel: "需要人数",
    experienceRequirementLabel: "经验要求",
    workDescriptionLabel: "工作描述",
    selectedWorkersLabel: "已选工人",
    viewAllWorkers: "查看全部{count}位工人",
    projectNature: "项目性质",
    workDates: "工作日期",
    workingDays: "工作日",
    paymentMethod: "结算方式",
    hourlyRateLabel: "时薪标准",
    estimatedHours: "预计工时",
    estimatedTotalCost: "预计总成本",
    notificationSettings: "通知设置",
    notificationMethodSelection: "通知方式选择",
    inAppNotification: "应用内通知",
    inAppNotificationDesc: "推送到工人的应用内消息",
    smsNotification: "短信通知",
    smsNotificationDesc: "发送短信到工人手机",
    aiPhoneNotification: "AI智能电话通知",
    aiPhoneNotificationDesc: "AI助手自动拨打电话，介绍项目详情",
    recommended: "推荐",
    replyDeadline: "回复时限",
    replyDeadlineDesc: "工人需要在设定时间内回复",
    smartAutoAssign: "智能自动分配",
    smartAutoAssignDesc: "如有工人拒绝，自动推荐替补工人",
    costBreakdown: "费用说明",
    totalEstimatedCost: "预计总费用",
    platformServiceFee: "平台服务费",
    paymentTiming: "付款时机",
    paymentAfterCompletion: "工作完成后统一结算",
    importantNotes: "重要说明",
    workerConfirmationTime: "工人将在{time}内回复确认",
    projectModifiable: "项目发送后仍可修改，修改会通知已确认的工人",
    largeProjectRecommendation: "建议大型项目选择AI电话通知提高响应率",
    sendProjectInvitation: "发送项目邀请给{count}位工人",
    saveAsDraft: "保存为草稿",
    backToModify: "返回修改项目信息",
    
    // Common Actions
    hint: "提示",
    
    // Time and Currency Units
    hour: "小时",
    day: "天",
    currency: "¥"
  },
  
  en: {
    // Welcome Screen
    appDescription: "Smart scheduling for contractors",
    valueProposition: "Smart scheduling for contractors\nand blue-collar professionals",
    signUpFree: "Sign Up Free",
    logIn: "Log In",
    joiningTeam: "Joining a Team?",
    
    // Auth Forms
    welcomeBack: "Welcome Back",
    createAccount: "Create an account",
    
    // Login Form
    continueWithPhone: "Continue with Phone Number",
    continueWithEmail: "Continue with Email",
    continueWithApple: "Continue with Apple",
    continueWithWechat: "Continue with WeChat",
    continueWithGoogle: "Continue with Google",
    
    // Registration Form
    email: "Email",
    password: "Password",
    phoneLogin: "Phone Verification Login",
    passwordLogin: "Password Login",
    phoneNumber: "Phone Number",
    phoneNumberPlaceholder: "Enter your phone number",
    passwordPlaceholder: "Enter password",
    verificationCode: "Verification Code",
    verificationCodePlaceholder: "Enter verification code",
    getVerificationCode: "Get Code",
    minimumCharacters: "Minimum of 6 characters",
    continue: "Continue",
    login: "Login",
    switchToPasswordLogin: "Use Password Login",
    switchToPhoneLogin: "Use Phone Login",
    alreadyHaveAccount: "Already have an account?",
    loginHere: "Log in",
    or: "OR",
    agreeToTerms: "I have read and agree to",
    
    // Company Information
    companyInformation: "Company Information",
    companyName: "Company Name",
    companyNameRequired: "Company Name *",
    industry: "Industry",
    industryRequired: "Industry *",
    selectIndustry: "Select industry",
    construction: "Construction",
    restaurant: "Restaurant",
    manufacturing: "Manufacturing",
    contactPerson: "Contact Person",
    contactPersonRequired: "Contact Person *",
    fullName: "Full name",
    businessAddress: "Business Address",
    businessAddressRequired: "Business Address *",
    enterBusinessAddress: "Enter business address",
    companyDescription: "Company Description",
    optional: "(Optional)",
    briefDescription: "Brief description of your company",
    
    // Phone Verification
    phoneVerification: "Phone Verification",
    phoneNumber: "Phone number",
    sendCode: "Send Code",
    resend: "Resend",
    enterVerificationCode: "Enter verification code",
    
    // Terms
    byTapping: "By tapping \\\"Continue\\\", you agree to our",
    privacyPolicy: "Privacy Policy",
    and: " & ",
    termsOfService: "Terms of Service",
    byContinuing: "By continuing, you agree to our",
    
    // Onboarding Flow
    welcomeToStaffLink: "Welcome to StaffLink",
    letsSetupAccount: "Let's set up your account",
    personalizeExperience: "We'll use your information to set up your account and personalize your experience",
    step1BasicInfo: "Basic Information",
    step2CompanyInfo: "Business Information",
    step3IndustrySelection: "Industry Selection", 
    step4BusinessDetails: "Business Details",
    step5Complete: "Complete Setup",
    contactName: "Contact Name",
    contactNamePlaceholder: "Enter your name",
    emailAddress: "Email Address",
    emailAddressOptional: "Email Address (Optional)",
    emailPlaceholder: "Enter email address",
    nextStep: "Next",
    
    // Step 2 Company Info
    tellUsAboutCompany: "Tell us about your business",
    companyInfoHelpUs: "This information will help us provide better service for you",
    companyNameRequired: "Business Name*",
    enterCompanyName: "Enter your business name",
    companyType: "Business Type",
    selectCompanyType: "Select business type",
    individualBusiness: "Individual Business",
    limitedCompany: "Limited Company", 
    partnership: "Partnership",
    other: "Other",
    businessAddressRequired: "Business Address*",
    enterBusinessAddress: "Enter your main business address",
    companyDescription: "Company Description",
    briefDescriptionCompany: "Brief description of your business (max 100 characters)",
    pleaseEnterCompanyName: "Please enter business name",
    pleaseEnterBusinessAddress: "Please enter business address",
    
    // Step 3 Industry Selection
    whatIndustryQuestion: "What industry are you mainly in?",
    selectIndustryCustomize: "Choose your main industry, we will customize the features for you",
    constructionRenovation: "Construction & Renovation",
    constructionDesc: "Plumbing, decoration, construction projects",
    foodService: "Food Service",
    foodServiceDesc: "Restaurants, hotels, tea restaurants, fast food",
    manufacturing: "Manufacturing",
    manufacturingDesc: "Electronics, textiles, food processing",
    logisticsWarehousing: "Logistics & Warehousing", 
    logisticsDesc: "Express sorting, warehouse management, cargo handling",
    otherServices: "Other Services",
    otherServicesDesc: "Cleaning, security, maintenance services",
    pleaseSelectIndustry: "Please select your industry",
    
    // Step 4 Business Setup
    whatSpecificBusinessType: "What specific type of business?",
    basedOnYourIndustrySelection: "Based on your Step 3 industry selection, please choose your specific business type",
    selectSpecificBusinessType: "Select your specific business type:",
    teamSizeQuestion: "Team Size (Optional)",
    howManyWorkersManage: "How many workers do you usually manage?",
    pleaseSelectBusinessType: "Please select business type",
    
    // Food Service Business Types
    teaRestaurant: "Tea Restaurant",
    fastFood: "Fast Food",
    hotPot: "Hot Pot",
    chineseRestaurant: "Chinese Restaurant",
    westernRestaurant: "Western Restaurant",
    coffeeShop: "Coffee Shop",
    hotelDining: "Hotel Dining",
    takeaway: "Takeaway",
    otherFood: "Other Food Service",
    
    // Construction Business Types
    homeDecoration: "Home Decoration",
    commercialDecoration: "Commercial Decoration",
    plumbingElectrical: "Plumbing & Electrical",
    renovationTeam: "Renovation Team",
    constructionTeam: "Construction Team",
    maintenanceService: "Maintenance Service",
    otherConstruction: "Other Construction",
    
    // Manufacturing Business Types
    electronicsMfg: "Electronics Manufacturing",
    textileMfg: "Textile Manufacturing",
    foodProcessing: "Food Processing",
    autoParts: "Auto Parts",
    plasticProducts: "Plastic Products",
    metalProcessing: "Metal Processing",
    otherManufacturing: "Other Manufacturing",
    
    // Logistics Business Types
    expressDelivery: "Express Delivery",
    warehouseMgmt: "Warehouse Management",
    cargoHandling: "Cargo Handling",
    freightTransport: "Freight Transport",
    sortingCenter: "Sorting Center",
    otherLogistics: "Other Logistics",
    
    // Other Service Business Types
    cleaningService: "Cleaning Service",
    securityService: "Security Service",
    repairService: "Repair Service",
    landscaping: "Landscaping",
    propertyMgmt: "Property Management",
    otherService: "Other Service",
    
    // Team Sizes
    teamSize1to10: "1-10 people",
    teamSize11to30: "11-30 people",
    teamSize31to50: "31-50 people",
    teamSize50plus: "50+ people",
    
    // Step 5 Complete
    completeSetup: "Complete Setup",
    lastStepSetPassword: "Final step, set a login password for your account",
    setLoginPassword: "Set Login Password",
    enterPassword6to20: "Set 6-20 character login password",
    confirmPassword: "Confirm Password",
    enterPasswordAgain: "Enter password again",
    completeRegistration: "Complete Registration",
    passwordMinLength: "Password must be at least 6 characters",
    passwordsDoNotMatch: "Passwords do not match",
    
    // Dashboard & Navigation
    home: "Home",
    goodMorning: "Good Morning",
    yourCompany: "Your Company",
    todayOverview: "Today's Overview",
    activeProjects: "Active Projects",
    workersToday: "Workers Today",
    completedTasks: "Completed Tasks",
    myProjects: "My Projects",
    seeAll: "See All",
    noProjectsYet: "No projects yet",
    clickToAddFirstProject: "Click to add your first project",
    newProject: "New Project",
    quickActions: "Quick Actions",
    viewSchedule: "View Schedule",
    manageWorkers: "Manage Workers",
    settings: "Settings",
    reports: "Reports",
    
    // Projects Screen
    projects: "Projects",
    searchProjects: "Search projects...",
    all: "All",
    active: "Active",
    completed: "Completed",
    startByCreatingFirstProject: "Start by creating your first project",
    createFirstProject: "Create First Project",
    
    // Workers Screen
    workers: "Workers",
    totalWorkers: "Total Workers",
    activeToday: "Active Today",
    available: "Available",
    searchWorkers: "Search workers",
    noWorkersYet: "No workers yet",
    addWorkersToStartScheduling: "Add workers to start scheduling",
    addFirstWorker: "Add First Worker",
    
    // Profile Screen
    profile: "Profile",
    userName: "User Name",
    editProfile: "Edit Profile",
    account: "Account",
    personalInfo: "Personal Information",
    companySettings: "Company Settings",
    changePassword: "Change Password",
    preferences: "Preferences",
    notifications: "Notifications",
    darkMode: "Dark Mode",
    off: "Off",
    support: "Support",
    help: "Help",
    feedback: "Feedback",
    about: "About",
    logout: "Logout",
    version: "Version",
    confirmLogout: "Confirm Logout",
    logoutConfirmMessage: "Are you sure you want to logout?",
    cancel: "Cancel",
    ok: "OK",
    
    // Create Project Screen
    createProject: "Create Project",
    projectName: "Project Name",
    enterProjectName: "Enter project name",
    projectAddress: "Project Address",
    enterProjectAddress: "Enter project address",
    startDate: "Start Date",
    endDate: "End Date",
    selectDate: "Select date",
    projectDescription: "Project Description",
    enterProjectDescription: "Enter project description",
    assignWorkers: "Assign Workers",
    scheduleWork: "Schedule Work",
    addPhotos: "Add Photos",
    pleaseEnterProjectName: "Please enter project name",
    pleaseEnterProjectAddress: "Please enter project address",
    success: "Success",
    projectCreatedSuccessfully: "Project created successfully",
    
    // Project Creation Wizard
    projectBasicInfo: "Project Basic Info",
    timeSchedule: "Time Schedule",
    workRequirements: "Work Requirements",
    selectWorkers: "Select Workers",
    confirmSend: "Confirm Send",
    pleaseSelectProjectType: "Please select project type",
    
    // Project Types - Industry Categories
    constructionRenovation: "Construction & Renovation",
    foodService: "Food & Beverage", 
    manufacturing: "Manufacturing",
    logisticsWarehousing: "Logistics & Warehousing",
    generalServices: "General Services",

    // Construction & Renovation
    homeRenovation: "Home Renovation",
    homeRenovationDesc: "Residential renovation, kitchen & bathroom remodeling",
    commercialRenovation: "Commercial Renovation", 
    commercialRenovationDesc: "Office, retail, restaurant renovation",
    electricalPlumbing: "Electrical & Plumbing",
    electricalPlumbingDesc: "Electrical wiring, plumbing installation, network cabling",
    maintenanceService: "Maintenance Service",
    maintenanceServiceDesc: "Equipment repair, troubleshooting, daily maintenance", 
    constructionProject: "Construction Project",
    constructionProjectDesc: "Civil construction, foundation work, structural engineering",

    // Food & Beverage
    coffeeTea: "Coffee & Tea",
    coffeeTeaDesc: "Coffee shops, tea houses, bubble tea stores",
    chineseCuisine: "Chinese Cuisine",
    chineseCuisineDesc: "Chinese restaurants, noodle shops, congee stores", 
    fastFood: "Fast Food",
    fastFoodDesc: "Fast food chains, takeaway restaurants",
    hotpotBBQ: "Hotpot & BBQ", 
    hotpotBBQDesc: "Hotpot restaurants, BBQ, spicy food",
    hotelDining: "Hotel Dining",
    hotelDiningDesc: "Hotel restaurants, banquet halls",

    // Manufacturing
    electronicsMfg: "Electronics Manufacturing",
    electronicsMfgDesc: "Phone assembly, electronic product manufacturing",
    textileMfg: "Textile Manufacturing", 
    textileMfgDesc: "Garment processing, textile production",
    foodProcessing: "Food Processing",
    foodProcessingDesc: "Food factories, beverage plants, packaging",
    mechanicalMfg: "Mechanical Manufacturing",
    mechanicalMfgDesc: "Equipment manufacturing, parts processing",
    packagingPrinting: "Packaging & Printing",
    packagingPrintingDesc: "Packaging materials, printing products",

    // Logistics & Warehousing  
    expressDelivery: "Express Delivery",
    expressDeliveryDesc: "Package sorting, delivery, pickup services",
    warehouseOps: "Warehouse Operations", 
    warehouseOpsDesc: "Inbound, outbound, inventory, sorting",
    movingService: "Moving Service",
    movingServiceDesc: "Residential moving, office relocation",
    freightHandling: "Freight Handling",
    freightHandlingDesc: "Long-haul freight, loading and unloading",
    inventoryMgmt: "Inventory Management", 
    inventoryMgmtDesc: "Warehouse management, inventory counting",

    // General Services
    cleaningService: "Cleaning Service",
    cleaningServiceDesc: "Office cleaning, residential cleaning, deep cleaning",
    securityService: "Security Service",
    securityServiceDesc: "Property security, event security, patrol", 
    landscaping: "Landscaping",
    landscapingDesc: "Green maintenance, landscape care, trimming",
    eventService: "Event Service",
    eventServiceDesc: "Exhibition setup, celebration events, temporary services",
    emergencyService: "Emergency Service",
    emergencyServiceDesc: "Emergency repair, temporary staffing, urgent needs",
    
    // Priority
    projectPriority: "Project Priority",
    normalPriority: "Normal",
    urgentPriority: "Urgent",
    emergencyPriority: "Emergency",
    sendNotification: "Send Notification",
    
    // Common
    required: "*",
    back: "Back",
    error: "Error",
    pleaseEnterName: "Please enter your name",
    pleaseEnterPhone: "Please enter phone number",
    freeTrialActivated: "Your free trial is now active",
    pleaseAgreeToTerms: "Please agree to the terms and privacy policy first",
    pleaseCompleteAllFields: "Please complete all required fields",
    pleaseGetVerificationCode: "Please get verification code first",
    verificationFailed: "Verification failed",
    incorrectVerificationCode: "Incorrect verification code",
    networkError: "Network error, please try again later",
    sendFailed: "Send failed",
    pleaseTryAgainLater: "Please try again later",
    loginSuccess: "Login successful",
    loginWith: "Login with",
    successful: "successful",
    loginFailed: "Login failed",
    
    // Smart Button Text
    startFillingProject: "Start filling project info",
    needToFillMore: "Need to fill {count} more",
    continueToTimeSchedule: "Continue to Time Schedule",
    continueToWorkRequirements: "Continue to Work Requirements",
    
    // Language
    language: "Language",
    chinese: "简体中文",
    english: "English",
    
    // Date and Time
    today: "Today",
    tomorrow: "Tomorrow",
    selectDate: "Select Date",
    selectTime: "Select Time",
    monday: "Mon",
    tuesday: "Tue", 
    wednesday: "Wed",
    thursday: "Thu",
    friday: "Fri",
    saturday: "Sat",
    sunday: "Sun",
    
    // Project Types
    projectType: "Project Type",
    projectTypeRequired: "Project Type*",
    selectProjectTypeFirst: "Please select the time nature of the project first",
    onetimeProject: "One-time Project",
    onetimeProjectDesc: "Complete within specified date range",
    recurringProject: "Recurring Project", 
    recurringProjectDesc: "Repeat at fixed times weekly",
    
    // Time Schedule
    projectPeriod: "Project Period",
    projectTimeRange: "Project Time Range",
    setProjectStartEnd: "Set the overall period for recurring projects",
    setProjectDates: "Set the start and end dates for the project",
    startDateRequired: "Start Date*",
    endDateRequired: "End Date*",
    selectStartDate: "Select start date",
    selectEndDate: "Select end date",
    dailyWorkTime: "Daily Work Time",
    eachWorkTime: "Each Work Time",
    setDailyTimeRange: "Set daily work time range",
    setEachTimeRange: "Set each work time range",
    startTime: "Start Time",
    endTime: "End Time",
    recurringWorkDays: "Recurring Work Days*",
    selectWeeklyDays: "Select weekly work days",
    timeNotes: "Time Notes",
    addTimeNotes: "Add special notes for time arrangement...",
    endDateBeforeStart: "End date cannot be before start date",
    fillCompleteTimeInfo: "Please fill in complete time schedule information",
    
    // Work Requirements
    requiredSkillsLabel: "Required Skills*",
    selectRequiredSkills: "Select skill types needed for the project",
    requiredWorkersLabel: "Required Workers*",
    selectWorkerCount: "Please select the number of workers needed",
    
    // Worker Count Options
    workerRange11to20: "11-20 people",
    workerRange21to50: "21-50 people", 
    workerRange51to100: "51-100 people",
    workerRange100plus: "100+ people",
    enterExactCount: "Please enter exact number",
    peopleCount: "people",
    customWorkerCount: "Custom worker count",
    experienceRequirement: "Experience Requirement",
    selectExperienceLevel: "Select experience level requirement for workers",
    workDescriptionLabel: "Work Description*",
    workDescriptionSubtitle: "Describe the work content to be completed in detail",
    workDescriptionPlaceholder: "Please describe work content, requirements and notes in detail...",
    salarySettings: "Salary Settings",
    selectPaymentMethod: "Select payment settlement method",
    hourlyPayment: "Hourly Payment",
    hourlyPaymentDesc: "Hourly work fee",
    dailyPayment: "Daily Payment", 
    dailyPaymentDesc: "Daily work fee",
    totalProjectPayment: "Total Project Payment",
    totalProjectPaymentDesc: "Total fee for the entire project",
    hourlyWage: "Hourly Wage ($/hour)",
    dailyWage: "Daily Wage ($/day)",
    projectTotal: "Project Total ($)",
    enterHourlyWage: "Enter hourly wage",
    enterDailyWage: "Enter daily wage", 
    enterProjectTotal: "Enter project total",
    specialRequirementsLabel: "Special Requirements",
    specialRequirementsSubtitle: "Other special requirements or notes",
    specialRequirementsPlaceholder: "E.g.: Need to bring own tools, special time requirements, etc...",
    fillCompleteWorkInfo: "Please fill in complete work requirements information",
    
    // Skills - Construction & Renovation
    plumbingInstall: "Plumbing Installation",
    electrician: "Electrician",
    carpentry: "Carpentry", 
    painting: "Painting",
    tiling: "Tiling",
    masonry: "Mason",
    waterproofing: "Waterproofing",
    ceilingInstall: "Ceiling Installer",
    glassInstall: "Glass Installer",
    plumber: "Plumber",
    pipeInstall: "Pipe Installer",
    weakCurrent: "Low Voltage Electrician",
    locksmith: "Locksmith",
    applianceRepair: "Appliance Repair",
    rebarWorker: "Rebar Worker",
    concreteWorker: "Concrete Worker",
    welding: "Welder",
    scaffoldWorker: "Scaffold Worker",
    surveyor: "Surveyor",
    
    // Skills - Food & Beverage
    barista: "Barista",
    waiter: "Waiter/Waitress",
    cashier: "Cashier",
    cleaner: "Cleaner",
    chef: "Chef",
    kitchenHelper: "Kitchen Helper",
    dishwasher: "Dishwasher",
    operator: "Operator",
    deliveryWorker: "Delivery Worker",
    bbqChef: "BBQ Chef",
    foodRunner: "Food Runner",
    
    // Skills - Manufacturing
    assemblyWorker: "Assembly Worker",
    solderer: "Solderer",
    qualityInspector: "Quality Inspector",
    packagingWorker: "Packaging Worker",
    machineOperator: "Machine Operator",
    sewingWorker: "Sewing Worker",
    cuttingWorker: "Cutting Worker",
    ironingWorker: "Ironing Worker",
    foodProcessor: "Food Processor",
    latheMachinist: "Lathe Machinist",
    assembler: "Assembler",
    materialHandler: "Material Handler",
    printer: "Printer",
    bookbinder: "Bookbinder",
    
    // Skills - Logistics & Warehousing
    courier: "Courier",
    sorter: "Sorter",
    loader: "Loader",
    driver: "Driver",
    stocker: "Stocker",
    forkliftOperator: "Forklift Operator",
    warehouseKeeper: "Warehouse Keeper",
    mover: "Mover",
    packer: "Packer",
    furnitureAssembler: "Furniture Assembler",
    
    // Skills - General Services
    janitor: "Janitor",
    cleaning: "Cleaner",
    windowCleaner: "Window Cleaner",
    carpetCleaner: "Carpet Cleaner",
    securityGuard: "Security Guard",
    doorman: "Doorman",
    patrolOfficer: "Patrol Officer",
    monitorOperator: "Monitor Operator",
    gardener: "Gardener",
    treeTrimmer: "Tree Trimmer",
    irrigationWorker: "Irrigation Worker",
    planter: "Planter",
    eventSetup: "Event Setup",
    audioTech: "Audio Technician",
    photographer: "Photographer",
    glazier: "Glazier",
    tempWorker: "Temporary Worker",
    
    // Experience Levels
    beginnerLevel: "Beginner",
    beginnerDesc: "Less than 1 year experience",
    intermediateLevel: "Intermediate",
    intermediateDesc: "1-3 years experience", 
    experiencedLevel: "Experienced",
    experiencedDesc: "3+ years experience",
    
    // Select Workers
    searchWorkerName: "Search worker name...",
    allWorkers: "All",
    recommendedWorkers: "Recommended",
    availableWorkers: "Available",
    selectedWorkers: "Selected",
    workersSelected: "{count} workers selected",
    workerBusyAlert: "This worker is currently busy and cannot be selected",
    availableStatus: "Available",
    busyStatus: "Busy",
    lastActive: "Last active",
    selectAtLeastOneWorker: "Please select at least one worker",
    noMatchingWorkers: "No matching workers found",
    adjustSearchFilter: "Try adjusting search criteria or filter options",
    
    // Confirm Send
    projectOverview: "Project Overview",
    projectNameLabel: "Project Name",
    projectTypeLabel: "Project Type", 
    projectAddressLabel: "Project Address",
    workTimeLabel: "Work Time",
    dailyTimeLabel: "Daily Time",
    workRequirementsLabel: "Work Requirements",
    requiredSkillsLabel: "Required Skills",
    requiredWorkersLabel: "Required Workers",
    selectedWorkersLabel: "Selected Workers",
    hourlyRateLabel: "Hourly Rate",
    estimatedCostLabel: "Estimated Cost",
    notificationSettings: "Notification Settings",
    notificationSubtitle: "Choose how to notify workers",
    inAppNotification: "In-App Notification",
    inAppNotificationDesc: "Push messages within the app",
    aiPhoneNotification: "AI Smart Phone Notification",
    aiPhoneNotificationDesc: "AI assistant automatically calls and intelligently introduces project details",
    aiFeatureHighlight: "✨ No manual coordination needed, saves time cost",
    smsNotification: "SMS Notification",
    smsNotificationDesc: "Send SMS to worker's phone",
    smsSelected: " (SMS notification selected)",
    aiPhoneSelected: " (AI phone notification selected)",
    recommended: "Recommended",
    replyDeadline: "Reply Deadline",
    replyDeadlineSubtitle: "How long workers need to reply",
    smartAutoAssign: "Smart Auto Assignment",
    smartAutoAssignDesc: "System automatically matches the most suitable workers for you",
    sendProjectInvitation: "Send Project Invitation",
    confirmSendTitle: "Confirm Send",
    confirmSendMessage: "Will send project invitation to {count} workers, continue?",
    
    // Common Actions
    hint: "Hint",
    
    // Time and Currency Units
    hour: "hour",
    day: "day", 
    currency: "$"
  }
};